dates = {
    "EN": {
        "months": (
            "January",
            "February",
            "March",
            "April",
            "May",
            "June",
            "July",
            "August",
            "September",
            "October",
            "November",
            "December"
        ),
        "days": (
            "Mo",
            "Tu",
            "We",
            "Th",
            "Fr",
            "Sa",
            "Su"
        ),
        "daily": "d"
    },
    "ES": {
        "months": (
            "Enero",
            "Febrero",
            "Marzo",
            "Abril",
            "Mayo",
            "Junio",
            "Julio",
            "Agosto",
            "Septiembre",
            "Octubre",
            "Noviembre",
            "Diciembre"
        ),
        "days": (
            "Lu",
            "Ma",
            "Mi",
            "Ju",
            "Vi",
            "Sa",
            "Do"
        ),
        "daily": "d"
    },
}

messages = {
    "EN": {
        "choose": "What language do you speak? (EN)",
        "welcome": "Welcome!",
        "current_cycle": "Current cycle",
        "past_cycles": "Past cycles",
        "exit": "Exit",
        "back": "Go back",
        "new_start_date": lambda d, m, y: f"This cycle has started on {dates['EN']['months'][m-1]} {d}, {y}",
        "add_new_habit": "Add a new habit",
        "habit_name": "Habit name",
        "habit_action": "Action",
        "habit_measurement": "Measurement/quantity/time",
        "habit_days": "Days of the week",
        "ask_new_habit": "Add another habit?",
        "yes": "Y",
        "no": "N",
        "cycle_created": "Cycle successfully created",
        "heading_date": lambda d, m, y: f"{dates['EN']['months'][m-1]} {d}, {y}",
        "mark_habits": "Mark habits",
        "setback_notes": "Setback notes",
        "cycle_review": "Cycle review",
        "habit_number": "Habit number",
        "day_mark": "Day to mark",
        "symbol": "Symbol",
        "marked": "Habit successfully marked",
    },
    "ES": {
        "choose": "¿Qué idioma hablas? (ES)",
        "welcome": "¡Bienvenido!",
        "current_cycle": "Ciclo actual",
        "past_cycles": "Ciclos anteriores",
        "exit": "Salir",
        "back": "Retroceder",
        "new_start_date": lambda d, m, y: f"Este ciclo ha iniciado el {d} de {dates['ES']['months'][m-1]} de {y}",
        "add_new_habit": "Agrega un hábito nuevo",
        "habit_name": "Nombre del hábito",
        "habit_action": "Acción",
        "habit_measurement": "Medida/cantidad/tiempo",
        "habit_days": "Días de la semana",
        "ask_new_habit": "¿Agregar otro hábito?",
        "yes": "S",
        "no": "N",  
        "cycle_created": "Ciclo creado exitosamente",
        "heading_date": lambda d, m, y: f"{d} de {dates['ES']['months'][m-1]} de {y}",
        "mark_habits": "Marcar hábitos",
        "setback_notes": "Notas de retrasos",
        "cycle_review": "Revisión del ciclo",
        "habit_number": "Número del hábito",
        "day_mark": "Day a marcar",
        "symbol": "Símbolo",
        "marked": "Hábito marcado exitosamente",
    }
}
